name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.5
      - uses: gradle/wrapper-validation-action@v1
