name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: gradle/wrapper-validation-action@v1
