name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          fetch-depth: 0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install cdxgen
        run: sudo npm install -g @cyclonedx/cdxgen
      - name: Run cdxgen
        run: cdxgen .  -o ./bom.json --deep --type java --resolve-class --recurse
      - name: View SBOM
        run: cat ./bom.json
      # Transmit a copy of our generated SBOM to Manifest
      - name: Transmit generated SBOM to Manifest
        uses: manifest-cyber/manifest-github-action@6bf8917b77e9d721d7971dfae955b968ab3bd817 # main
        id: transmit
        with:
          apiKey: ${{ secrets.MANIFEST_API_KEY }}
          bomFilePath: "./bom.json"
          sbom-version: ""
          sbom-name: testing-go-mod-name
          sbom-output: cyclonedx-json
 